
---
- name: "Install Nginx"
  hosts: node01
  become: true
  vars:
    nginx_port: 8080
    apt_required_packages:
      - nginx

  tasks:
    - name: "install required packages"
      apt:
        name: "{{ apt_required_packages }}"
        state: present
      notify: Restart Nginx

    - name: "Copy nginx.conf"
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: "Copy index.html"
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html

    - name: "Copy default.conf"
      template:
        src: ../templates/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf

    - name: "Enable new site"
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted