---
- name: install Docker
  hosts: docker
  vars:
    DOCKER_COMPOSE_VERSION: 1.29.2
  become: true

  tasks:
    - name: install dipendenses
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
        force_apt_get: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - lsb-release

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: add repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable
        state: present

    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
        force_apt_get: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: make sure that docker was started and enabled
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted
